#!/usr/bin/env bash
set -euo pipefail
ROOT="${1:-$HOME/Weall_node_MVP}"
cd "$ROOT"

FRONT="weall_node/frontend"
[ -d "$FRONT" ] || { echo "Missing $FRONT"; exit 1; }

# Ensure .env has keys (reuse if present)
if ! grep -q '^VITE_API_BASE=' .env 2>/dev/null; then
  cat >> .env <<'ENV'
VITE_API_BASE=http://127.0.0.1:8000
VITE_IPFS_API=http://127.0.0.1:5001
VITE_IPFS_GATEWAY=https://ipfs.io
ENV
fi

# Read values from .env
API_BASE="$(grep -E '^VITE_API_BASE=' .env | tail -n1 | cut -d= -f2-)"
IPFS_API="$(grep -E '^VITE_IPFS_API=' .env | tail -n1 | cut -d= -f2-)"
IPFS_GATEWAY="$(grep -E '^VITE_IPFS_GATEWAY=' .env | tail -n1 | cut -d= -f2-)"

# Write env.js
cat > "$FRONT/env.js" <<JS
// Auto-generated by 11_env_and_api_shim.sh
window.ENV = Object.assign(window.ENV || {}, {
  VITE_API_BASE: "${API_BASE}",
  VITE_IPFS_API: "${IPFS_API}",
  VITE_IPFS_GATEWAY: "${IPFS_GATEWAY}"
});
JS

# api_shim.js: route /api/* to VITE_API_BASE
cat > "$FRONT/api_shim.js" <<'JS'
(function(){
  const base = (window.ENV && window.ENV.VITE_API_BASE) || '';
  if (!base) return;
  const origFetch = window.fetch.bind(window);
  window.fetch = function(resource, init){
    try{
      if (typeof resource === 'string' && resource.startsWith('/api')) {
        resource = base.replace(/\/+$/,'') + resource;
      } else if (resource && resource.url && typeof resource.url === 'string' && resource.url.startsWith('/api')) {
        resource = base.replace(/\/+$/,'') + resource.url;
      }
    }catch(e){}
    return origFetch(resource, init);
  };
})();
JS

# Inject env.js + api_shim.js into each top-level HTML file (once)
for f in $(find "$FRONT" -maxdepth 1 -type f -name "*.html"); do
  if ! grep -q 'env.js' "$f"; then
    if grep -qi '</head>' "$f"; then
      sed -i '/<\/head>/i \  <script src="env.js"></script>\n  <script src="api_shim.js"></script>' "$f"
      echo "patched(head): $f"
    else
      sed -i 's#<body[^>]*>#&\n  <script src="env.js"></script>\n  <script src="api_shim.js"></script>#I' "$f"
      echo "patched(body): $f"
    fi
  fi
done

echo "[✓] env.js + api_shim.js installed and injected."
