from __future__ import annotations

import logging
import os
from pathlib import Path
from typing import List

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import RedirectResponse, Response
from fastapi.staticfiles import StaticFiles

from weall_node.routers.auth_session import router as auth_session_router
from weall_node.routers.auth_static import router as auth_router

# ---------------------------------------------------------------------------
# Settings (YAML-backed via weall_settings, with a safe dev fallback)
# ---------------------------------------------------------------------------

try:
    # Prefer local module at repo root (generated by your setup scripts)
    from weall_settings import settings
except Exception as e:
    logging.warning("weall_settings not found or failed to load: %s", e)

    class _Fallback:
        class _Server:
            host = "0.0.0.0"
            port = 8000
            cors_origins: List[str] = ["*"]

        class _JWT:
            secret_key = "dev"
            algorithm = "HS256"
            expire_minutes = 60

        class _Log:
            level = "INFO"
            json = True

        server = _Server()
        jwt = _JWT()
        logging = _Log()
        DATA_DIR = Path(".")

    settings = _Fallback()  # type: ignore[assignment]

# Configure base logging level from settings (if provided)
log_level_name = getattr(getattr(settings, "logging", None), "level", "INFO")
logging.basicConfig(
    level=getattr(logging, str(log_level_name).upper(), logging.INFO)
)

# ---------------------------------------------------------------------------
# IPFS client init (safe/no-op if daemon isn't running)
# ---------------------------------------------------------------------------

from weall_node.ipfs.client import init_default_client  # noqa: E402

# ---------------------------------------------------------------------------
# Core API routers
# ---------------------------------------------------------------------------

from .api import (  # noqa: E402
    poh,
    governance,
    treasury,
    rewards,
    storage,
    health as health_router,
    content,
    sync,
    ledger,
    reputation,
    messaging,
    disputes,
    pinning,
    verification,
    chain,
    compat,
    validators,
    operators,
    consensus,
    recovery,
    faucet,
    p2p_overlay,   # <-- added
)

# ---------------------------------------------------------------------------
# App initialization
# ---------------------------------------------------------------------------

app = FastAPI(
    title="WeAll Node API",
    description=(
        "Backend node API for the WeAll network: "
        "governance, Proof of Humanity, ledger, content, disputes, treasury, etc."
    ),
    version="0.1.0",
)

# ---------------------------------------------------------------------------
# Auth routers (session + dev email code)
# ---------------------------------------------------------------------------

app.include_router(auth_session_router)  # /auth/apply, /auth/check
app.include_router(auth_router)         # /auth/send-code, /auth/verify (dev / non-prod)


# ---------------------------------------------------------------------------
# Core protocol routers
# ---------------------------------------------------------------------------

# Content / feed / rewards / chain
app.include_router(content.router)      # /content/...
app.include_router(rewards.router)      # /rewards/...
app.include_router(chain.router)        # /chain/...
app.include_router(faucet.router)

# Governance & treasury
app.include_router(governance.router)   # /governance/...
app.include_router(treasury.router)     # /propose, /proposals, etc.

# Validators / operators / consensus
app.include_router(validators.router)   # /validators/...
app.include_router(operators.router)    # /operators/...
app.include_router(consensus.router)    # /consensus/...

# Messaging / sync / ledger / storage
app.include_router(messaging.router)    # /messaging/... + legacy /content alias
app.include_router(sync.router)         # sync / p2p wiring
app.include_router(ledger.router)       # ledger inspection endpoints
app.include_router(storage.router)      # /storage/... (IPFS / local)

# P2P overlay (identity & peers)
app.include_router(p2p_overlay.router)  # /p2p/...

# Reputation & PoH (explicit)
app.include_router(reputation.router)   # /reputation/...
app.include_router(poh.router)          # /poh/...

# Pinning / verification / recovery / compat
app.include_router(pinning.router)      # /pin/...
app.include_router(verification.router) # /verification/...
app.include_router(recovery.router)     # /recovery/...
app.include_router(compat.router)       # legacy endpoints (/register, /show_posts, ...)


# ---------------------------------------------------------------------------
# Health API (mounted under /api/health)
# ---------------------------------------------------------------------------

# health_router.router exposes GET "/" and "/metrics" – we mount it under /api/health
app.include_router(
    health_router.router,
    prefix="/api/health",
    tags=["health"],
)


# ---------------------------------------------------------------------------
# CORS configuration
# ---------------------------------------------------------------------------

app.add_middleware(
    CORSMiddleware,
    allow_origins=getattr(settings.server, "cors_origins", ["*"]),
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ---------------------------------------------------------------------------
# Static frontend
# ---------------------------------------------------------------------------

app.mount(
    "/frontend",
    StaticFiles(directory="weall_node/frontend", html=True),
    name="frontend",
)


# ---------------------------------------------------------------------------
# Lifecycle: startup hooks
# ---------------------------------------------------------------------------

@app.on_event("startup")
async def _startup() -> None:
    """
    Node startup hook:
    - Initialize IPFS client (if daemon is reachable).
    """
    try:
        init_default_client()
    except Exception as exc:  # pragma: no cover - defensive only
        logging.warning("IPFS client init failed on startup: %s", exc)


# ---------------------------------------------------------------------------
# Routing helpers: index / root / favicon
# ---------------------------------------------------------------------------

@app.get("/index/", include_in_schema=False)
def _redir_index_slash() -> RedirectResponse:
    """Keep old /index/ URLs working by redirecting to the SPA home."""
    return RedirectResponse(url="/frontend/index.html", status_code=307)


@app.get("/index", include_in_schema=False)
def _redir_index_noslash() -> RedirectResponse:
    """Keep old /index URLs working by redirecting to the SPA home."""
    return RedirectResponse(url="/frontend/index.html", status_code=307)


@app.get("/favicon.ico", include_in_schema=False)
def _favicon() -> Response:
    """
    Serve favicon.ico from repo root if present.
    Fast 404 if not.
    """
    try:
        with open("favicon.ico", "rb") as f:
            return Response(content=f.read(), media_type="image/x-icon")
    except FileNotFoundError:
        return Response(status_code=404)


@app.get("/", include_in_schema=False)
async def root(request: Request):
    """
    Genesis-aligned entrypoint with session-aware routing.

    - API / programmatic clients:
        Return a JSON descriptor (no redirects) for predictable automation.

    - Browsers / humans WITHOUT a session:
        Redirect to onboarding.html (explains PoH tiers & flow).

    - Browsers / humans WITH a session cookie:
        Redirect straight to frontend/index.html (home feed).
    """
    accept = (request.headers.get("accept") or "").lower()
    cookie_header = request.headers.get("cookie") or ""
    cookie_lower = cookie_header.lower()

    # Heuristic: treat these cookies as "logged-in" indicators.
    has_session = any(
        token in cookie_lower
        for token in (
            "weall_session=",
            "session_id=",
            "weall_auth=",
        )
    )

    # API-style clients get JSON instead of redirects
    if "application/json" in accept and "text/html" not in accept:
        return {
            "status": "ok",
            "node": "weall-genesis",
            "message": "WeAll Genesis node online.",
            "onboarding_url": "/frontend/onboarding.html",
            "login_url": "/frontend/login.html",
            "home_url": "/frontend/index.html",
            "spec": {
                "poh_tiers": [1, 2, 3],
                "reputation_range": [-1.0, 1.0],
                "tier3_threshold": 0.75,
            },
        }

    # If we appear to have a session, send user to home feed
    if has_session:
        return RedirectResponse(url="/frontend/index.html", status_code=302)

    # Otherwise show Genesis onboarding
    return RedirectResponse(url="/frontend/onboarding.html", status_code=302)
