// Auto-generated by 11_env_and_api_shim.sh
window.ENV = Object.assign(window.ENV || {}, {
  VITE_API_BASE: "http://127.0.0.1:8000",
  VITE_IPFS_API: "http://127.0.0.1:5001",
  VITE_IPFS_GATEWAY: "https://ipfs.io"
});
