# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weall/v1/block.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'weall/v1/block.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from weall.v1 import common_pb2 as weall_dot_v1_dot_common__pb2
from weall.v1 import tx_pb2 as weall_dot_v1_dot_tx__pb2
from weall.v1 import receipt_pb2 as weall_dot_v1_dot_receipt__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14weall/v1/block.proto\x12\x08weall.v1\x1a\x15weall/v1/common.proto\x1a\x11weall/v1/tx.proto\x1a\x16weall/v1/receipt.proto\"\xcd\x01\n\x0b\x42lockHeader\x12\x0e\n\x06height\x18\x01 \x01(\x04\x12\x11\n\tprev_hash\x18\x02 \x01(\x0c\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\t\x12\r\n\x05\x65poch\x18\x04 \x01(\x04\x12\x10\n\x08proposer\x18\x05 \x01(\x0c\x12,\n\rproposed_time\x18\x06 \x01(\x0b\x32\x15.weall.v1.TimestampMs\x12\x0f\n\x07tx_root\x18\n \x01(\x0c\x12\x15\n\rreceipts_root\x18\x0b \x01(\x0c\x12\x12\n\nstate_root\x18\x0c \x01(\x0c\"\x9f\x01\n\x05\x42lock\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.weall.v1.BlockHeader\x12!\n\x03txs\x18\x02 \x03(\x0b\x32\x14.weall.v1.TxEnvelope\x12%\n\x08receipts\x18\x03 \x03(\x0b\x32\x13.weall.v1.TxReceipt\x12\x12\n\nblock_hash\x18\x64 \x01(\x0c\x12\x11\n\tsignature\x18\x65 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weall.v1.block_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BLOCKHEADER']._serialized_start=101
  _globals['_BLOCKHEADER']._serialized_end=306
  _globals['_BLOCK']._serialized_start=309
  _globals['_BLOCK']._serialized_end=468
# @@protoc_insertion_point(module_scope)
