# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: weall/v1/events.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'weall/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15weall/v1/events.proto\x12\x08weall.v1\"\x1a\n\x02KV\x12\t\n\x01k\x18\x01 \x01(\t\x12\t\n\x01v\x18\x02 \x01(\t\"L\n\x05\x45vent\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.weall.v1.EventType\x12 \n\nattributes\x18\x02 \x03(\x0b\x32\x0c.weall.v1.KV*\xb8\x03\n\tEventType\x12\x15\n\x11\x45VENT_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x43ONTENT_POSTED\x10\n\x12\x11\n\rCONTENT_LIKED\x10\x0b\x12\x15\n\x11\x43ONTENT_COMMENTED\x10\x0c\x12\x14\n\x10\x43ONTENT_REPORTED\x10\r\x12\x11\n\rGROUP_CREATED\x10\x14\x12\x10\n\x0cGROUP_JOINED\x10\x15\x12\x0e\n\nGROUP_LEFT\x10\x16\x12\x18\n\x14TREASURY_TRANSFERRED\x10\x1e\x12\x14\n\x10PROPOSAL_CREATED\x10(\x12\x12\n\x0ePROPOSAL_VOTED\x10)\x12\x16\n\x12PROPOSAL_FINALIZED\x10*\x12\x12\n\x0e\x44ISPUTE_OPENED\x10\x32\x12\x1e\n\x1a\x44ISPUTE_EVIDENCE_SUBMITTED\x10\x33\x12\x17\n\x13\x44ISPUTE_JUROR_VOTED\x10\x34\x12\x15\n\x11\x44ISPUTE_FINALIZED\x10\x35\x12\x11\n\rPOH_SUBMITTED\x10<\x12\x14\n\x10POH_TIER_UPDATED\x10=\x12\x10\n\x0cROLE_GRANTED\x10>\x12\x10\n\x0cROLE_REVOKED\x10?b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weall.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTTYPE']._serialized_start=142
  _globals['_EVENTTYPE']._serialized_end=582
  _globals['_KV']._serialized_start=35
  _globals['_KV']._serialized_end=61
  _globals['_EVENT']._serialized_start=63
  _globals['_EVENT']._serialized_end=139
# @@protoc_insertion_point(module_scope)
